defaults:
    - base
    - _self_

model_path: haoranli-ml/genvf-v9_1-nextN
model_revision: v00.00-step-000300
# Uncomment to skip test set rollouts
eval_every_n_versions: 2000

# NOTE: In 9_1, we remove squash reward and change judge prompt to genvf_v7_nextN (since in v6 it penalizes overly long bullet poiont which we 
# want now)

# samples_per_step = gradient_accumulation_passes × train_batch_size =16x16=256
# question_per_update = samples_per_step/attemptes = 256/8=32
# gradietn accmuluation per gpu = gradient_accumulation_passes // num_GPUs*train_fraction = 16//(1*4)=4

finetune:
  keep_intermediate_checkpoints: false # to save disk space
  attempts: 8
  train_batch_size: 16
  valid_batch_size: 16
  gradient_accumulation_passes: 16
  seq_length: 43000
  seq_parallel: 2
  save_checkpoint_steps: 10
  max_train_steps: 700 # 228 steps per epoch
  push_to_hub: true
  hub_model_id: haoranli-ml/genvf-v9_1-nextN-start-300
  hub_model_revision: v00.00
  hub_ignore_patterns:
    - "*.pt"
    - "*.pth"

llm:
  parameters:
    max_tokens: 16384
    temperature: 0.7
    top_p: 0.8
    top_k: 20
  reasoning_delimiters: ["</think>"]
  wandb_table:
    enabled: true
    keep_last_k_groups: 10
    log_every_n_groups: 50
# Sampling params taken from Qwen3 tech report: https://arxiv.org/abs/2505.09388
test_llm:
  parameters: 
    max_tokens: 16384
    temperature: 0.7
    top_p: 0.8
    top_k: 20

llm_grader:
  name: openai/gpt-oss-20b # or gpt-oss-20b-reh if running via inference endpoints
  # vllm_kwargs will be ignored if grader is used with url
  vllm_kwargs:
    num_nodes: 1
    data-parallel-size: 8
    tensor-parallel-size: 1
    max-num-batched-tokens: 16384
    max-num-seqs: 16
    max-model-len: 32768
    gpu-memory-utilization: 0.85
  sampling_kwargs:
    temperature: 1.0
    max_output_tokens: 32768
    reasoning:
      effort: medium
  prompt_name: genvf_v7_nextN
  reasoning_delimiters: ["</think>"]
  wandb_table:
    enabled: true
    keep_last_k_groups: 10
    log_every_n_groups: 50

wandb:
  wandb_dir: /project/flame/aviralku/wandb_logs/
  wandb_entity_name: GenVF
  wandb_project_name: GenVF_train
  wandb_resume: always

actor:
  llm_max_rollouts: 32 # 64 will blow up for H100
  system_prompt: null
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathProofEnvironment
  model_name: ${llm_grader.name}
  sampling_kwargs: ${llm_grader.sampling_kwargs}
  prompt_name: ${llm_grader.prompt_name}
dataset_loader: pipelinerl.domains.math.load_datasets
train_dataset_names:
  - hub_id: haoranli-ml/genvf-filtered-proof-graded_score7_only-K4-summaries-nextN-prl-train
    split: train
  - hub_id: haoranli-ml/genvf-filtered-answer-only-K4-summaries-nextN-prl-train
    split: train
test_dataset_names:
  - hub_id: haoranli-ml/genvf-filtered-proof-graded_score7_only-K4-summaries-nextN-prl-train # 24 verified proof only
    split: test
  - hub_id: haoranli-ml/genvf-filtered-answer-only-K4-summaries-nextN-prl-train
    split: test

vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${actor.llm_max_rollouts}
    max-num-batched-tokens: 16384
    max-model-len: ${finetune.seq_length} # newly added, i suspect not setting this will cause vllm to collapse
    enable-chunked-prefill: ""
    no-enable-prefix-caching: ""  # newly added, to prevent massive memory usage -> entropy blow up
    return-tokens-as-token-ids: ""
    tensor-parallel-size: 1
    pipeline-parallel-size: 1
    generation-config: vllm

world:
  replicas: 1
  actor_fraction: 4
  preprocessor_fraction: 0
  finetune_fraction: 4
  env_replicas: 1
  actor_group_port: 9000
  environment_start_port: 7777
