defaults:
    - base
    - _self_

model_path: Qwen/Qwen3-4B-Instruct-2507
eval_every_n_versions: 120

finetune:
  attempts: 8
  train_batch_size: 8
  valid_batch_size: 8
  gradient_accumulation_passes: 4
  learning_rate: 1.0e-6
  max_train_steps: 360
  rl:
    kl_coef: 0.0
    entropy_bonus: 0.0
  seq_length: 23050
  seq_parallel: 1
  save_checkpoint_steps: 30
  push_to_hub: true
  hub_model_id: haoranli-ml/VF_no_future_condition_action_items
  hub_model_revision: v00.00
  hub_ignore_patterns:
    - "*.pt"
    - "*.pth"

llm:
  parameters:
    max_tokens: 8192 
    temperature: 0.8
# Sampling params taken from Qwen3 tech report: https://arxiv.org/abs/2505.09388
test_llm:
  parameters: 
    max_tokens: 8192
    temperature: 0.8 
    top_p: 0.8
    top_k: 20

actor:
  llm_max_rollouts: 32 # Larger values exhaust the KV cache and lead to preemptions
  rollout_policy: pipelinerl.domains.math.generate_math_rollout
  system_prompt: null
  task_template: |-
    {task}
environment:
  _target_: pipelinerl.domains.math.MathEnvironment
dataset_loader: pipelinerl.domains.math.load_datasets

wandb:
  wandb_dir: /project/flame/haoranl4/prl/wandb_logs/
  wandb_name: no_future_condition_action_items
  wandb_entity_name: GenVF
  wandb_project_name: GenVF_train
  wandb_resume: always

wandb_table:
  enabled: false

train_dataset_names:
  - hub_id: haoranli-ml/VF_8k_distr_out_cdf_bin_future_prompts
    split: train_no_future_condition_action_items
    use_hl_gauss: true
    sigma: 0.12
test_dataset_names:
  - hub_id: haoranli-ml/VF_8k_distr_out_cdf_bin_future_prompts
    split: test_no_oracle_no_future_condition_action_items
    use_hl_gauss: true
    sigma: 0.12

vllm_config:
  use_v1: false
  vllm_kwargs:
    dtype: bfloat16
    gpu-memory-utilization: 0.9
    num-scheduler-steps: 1
    disable-log-requests: ""
    disable-frontend-multiprocessing: ""
    max-num-seqs: ${actor.llm_max_rollouts}
    max-num-batched-tokens: 65536
    enable-chunked-prefill: ""
    return-tokens-as-token-ids: ""
    tensor-parallel-size: 1
    pipeline-parallel-size: 1
    generation-config: vllm

world:
  replicas: 1
  actor_fraction: 4
  preprocessor_fraction: 0
  finetune_fraction: 4
  env_replicas: 1
  actor_group_port: 9000
  environment_start_port: 7777
